apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:tiYAuRXjgdbudULk0zZ2mt0LP/4ZnQjStkiswpFQ+sG4eueVDkJ9TA==,iv:+XvHX/dxvCBlklhFLx8yGhDUrBBh7Bs4WMeJsLK4rXo=,tag:rO+M4w5J43AZkrgDzdQv5g==,type:str]
sops:
  age:
    - recipient: age1y7nfred6vj25amp64z3x7m5d7vsuxvh5740zn0y0wdrx52tmrv3qwvhhua
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NnpVTDBLMUpTZUJiUTNN
        NW5vMkgwK3RmcllKdE5FQU1rMjNFcTVQS0FrCmZ5T3JtQXVDYnZyS2dQSGlHeFBz
        NVc1TGk5QjVvNzI0dHpKNUtqeXJsRWMKLS0tIEcyV1NVaXFxd1JsVGkwUjM3K2pY
        MHUrMERaWU5DU2pnV21lRXJYOG1CQzgKHA9I7HlfGPB+SOlYLBb614k0vm3Bcltk
        jCurfXxQGWY/5jeJmsBU8TdnfQhT+mJc2ny3QEN/ZC9GEewEWLGYfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T12:30:06Z"
  mac: ENC[AES256_GCM,data:zY6q2epOMHQvwfGsf7T0fYF8BwRGn/3wEI9SaVkMmV9eHAQF3M17HSXaTNIugGMH+l1aeebP0cGupZV13vMn7+M8beyqhkNo2RmmDTXFCelYLOG4QYXVzLq7nKafQ2UthdT9sf06qOXjcI1tSn8MnVfxzaS+WKTPNVdEsvGVRUg=,iv:0XMGzBGqvUbzX/EMlFxpdROIeHEDK85BlpgZLras1sk=,tag:yQdWthtFJnhgJatBRLc4pg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
