apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:n93V0+8QBpg0,iv:ZWrmDYUOdsC81oRZ1vH3eKslYnCA01qZOQiwfQ2zgmc=,tag:OVNt14ZDOavAlgS7XzEyfw==,type:str]
sops:
  age:
    - recipient: age1y7nfred6vj25amp64z3x7m5d7vsuxvh5740zn0y0wdrx52tmrv3qwvhhua
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZ0ZFbk9mMmVZVXE3RU9K
        Sy9rTytSOWkreERyZjBlZU1hUDYwZ1A5V1U0Cml6aDhUMWw4dzdJTFJzaHpNY3pz
        bHdDTndQOThFUWN3eWlrYTdQNXRXaE0KLS0tIDFUeEdZNnZMOEtGQUFtQVlXWS9C
        azEwV3d2ckFWRkdJRnpwbjVZQWI4VDQKtjmmCIdvIYzXwAyc0uvoCdywrPu1O/lk
        uc2Yo71OwaQur/tWSHD6XarKBUuwzQwtUjKH0IlkWHzuSVq6UYt8yA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T12:30:06Z"
  mac: ENC[AES256_GCM,data:LDtaS7sLC9KqA3xYv9cDooYr6MSQqRybFWekOy3OJ0sNn1JhvQ0bK4Y9+LZ7+BMH9ZP9UjvLxSsRUeREUtWUgfDu0Qt8VSRDJB63SFs/ujWcJ4GrvSeDijrBj/jeCW3gLrwh5tq4m8NEBuKTS3pQv0BWFerj6MvIoxztMtbHOFI=,iv:Ph1R5XnXqRgG/7i6M/DPRggeKwiCKXyE8O/17s6/wlA=,tag:nAlH0ydzCGWnOss5qVKfnw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
