apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:3ZhAuRK3R5S1mRFWMdFv0kJVzNW0j44CtnMGNxhbwmA=,iv:mQISB/8Z+Yffo1l4MbVSERt86OKe7VQvuER+j2gN42c=,tag:yFsfOs0b3uhfuJ/cvGe7Jw==,type:str]
sops:
  age:
    - recipient: age1y7nfred6vj25amp64z3x7m5d7vsuxvh5740zn0y0wdrx52tmrv3qwvhhua
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MG9PZEo1MGN2d0d0RzZS
        SC9jRTNGN0cvS1pkZkJ3WXlyMnB5VXZNMjNZCk5NcEpqdllnSEJvbFA5M1k0UXN5
        eE5UUm5QWmlJZWtiY0hoRUhpQkNIWVUKLS0tIGJCTEZ5SUNSUVlxK3FpRW8wU2JM
        VlIwaVNVcGpod0p4RXR3eUZ2Ynh3QkEK3tKmrIxUL7qYKd0eAuMJDxEkXlUKUZ9i
        bB+zr4sFNzgktg3G4iUsS797aLFYQHmnNp3pKroXk/hTSbFg/G0PFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T12:30:06Z"
  mac: ENC[AES256_GCM,data:RPeKI7lPxUbttVDzMb8BpX3mRifQtsJMSgqH34ukPSF9PeupP3567kN6aBqJKQG8pBETYaOghv+qbG+e0Q82eKseqGlwQviUx+ptMCzmSdzV6AqkEbpACYMN7D7dHzx0RdhSZA7AuFJRbZTtUufBgVtZConJ9ji8uAXN2Yzj+O8=,iv:fpRQH/9g8PCHCPhDV4mVTkcntDeq/S88EJdFzFm6wKI=,tag:fna7MOrTQwWXvCFZWk+Erw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
