apiVersion: v1
kind: Secret
metadata:
  name: r2-backup-credentials
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:9rsYxNk3k2S4YQFYQAAYzqucg3R0mmtMNUvq1qax3j8=,iv:tzXh8gzlqUXFSlwWUXYVE1dwXi6XjDSCSVUTRHWRv1s=,tag:1Y5Dr1B45hp1U+XydOwHfA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DGypjyZGfm5hfD409sqkXQ1cefaxfofTmEXfEbDz6pdzzH89bqyXOSrbKupDKeYnf6r6PreluyHEnpdRsA5Wag==,iv:nAuwW2JYtPMjtpLoaAT4DeEU5yy/jQshAS88OzpMyto=,tag:F7JUvLBF6P/3gotGCkVVig==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:hnZDqJ+vP1bVWHNJm4ru+huDO8NCENRxfz8oHbt52qhU0PyC4IN0heu3rnlw2A8hWD1THpkbABn1bmOPHvoPgxQ=,iv:NC+scDh9wlptjhZxK6YYOwNpIUIuQ99XwGGwaJTK8SU=,tag:e63FomD+YHceIJKSun+yhQ==,type:str]
sops:
  age:
    - recipient: age1y7nfred6vj25amp64z3x7m5d7vsuxvh5740zn0y0wdrx52tmrv3qwvhhua
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKb2YvWTVTNWFHQ2UySmNo
        eUZGb2F0TFBzT3U2VnpxM3Baa0RSRjduT3dvCnpqMnNMVURTOTlrSVM0bVdlU3Ey
        SGxHRVV1WDVlZzV5WTNFbyttMUxFeFEKLS0tIFVYVmM0OW0rcUs1Vnk1Vy9PSG9y
        YllXRGVOVDVmZSs0MkYvRHR0MkxBMmsK7Pq9MERjSXZQsmL+tv5bmZ5HpJHpatTf
        30WDo64Q4q46+PfDwjRe9MJJkaQpObXIez67o8KiDu2dVZLVh/crDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T15:24:44Z"
  mac: ENC[AES256_GCM,data:alDGwLzulF+JwSOERGL8nEVQQyPgP+AAZjNbCC3FvdfKOJwnNBcdPy6nvNomFFrS2yldvTfKieHT4rHtjdoonjqOXMWOiKNx5vhKqVmk2jCFj2MHmruK/OIoBIbuEUp+383D+D1NzLMZ22lyjuDS4ueUqhyvOjpxB2vtqDawUBk=,iv:mGUwVHd3qE8AkNcMXGkXdB/dU4HmyLmi4MDAtzgPHKQ=,tag:7j5/zGZS7G+fQiWU/aETiQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
