apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:1OBcIts0IIMNg98v69O66GcaSTXpchKLjbBSFvHSBHlTgsMWbXR0gpdjmFzuHAeUTrF7GecgkqGgAwSUUyg38P355/YjYc9pZ8DYxS048Od2BIZJlYgKlCoOgPAaWKqOX5eS0IahErpUCeILEgqofU6BC/bsgfGAJeM+hVUaWadl960zV3m3LIBgBH1qPfBOmeW/MN0+mlRzGrqeOHYXZxlurJrXKCL7NMvsGLz88CrmLROm,iv:8pkd9DsySqL1JjkmCiGcIJZe1/JnZQ8hSThnxp+JuEo=,tag:EaE9B6Ss8a0UNxnkqT9nlg==,type:str]
sops:
  age:
    - recipient: age1y7nfred6vj25amp64z3x7m5d7vsuxvh5740zn0y0wdrx52tmrv3qwvhhua
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3b05mSjQ1N0FkK1djMXlB
        ZVNGb2VXbElNUXRuYmIwTGhNMTZqaGs2NzBnClRBclJJcWN3dHpZY29YOWdSNUs1
        RUJGaUZud2dhaVVYTk5Pdkxib25XRWMKLS0tIFJveUt4UHg5d0RpTlBtSHNkV0Qx
        QkhsWnRvUmNHMWlvVmM1VHpRSkZFVFEK2saxWdTZ9g882uybsvTNIxkXXmwD6RQP
        Bwje5sgIUp2POpb+6nhm0SiJl+dO40CdZ5RzNQscLVDd/bMTNy6NDg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T12:30:06Z"
  mac: ENC[AES256_GCM,data:3+fLH8gtxtW6nZFcX9C6KicpCcccWmWhCy6OvIKViSFt6GH7Bgd6n+oJRxLxHbafzJgHfjGMMMKJUDTgutiBx7bTkQBipnhrf0ic4f1AYFsRtEpEDbIcUYfGWsWySzvab9AwurIPsLvVYBqPt5sfnMWoxxLNG2z5mylpj6SYhi0=,iv:U3ofT4CPMZYaRfH1k6Mnj2AbQD1dGbHNgX+iDy4/akE=,tag:8FGSECaEL5TUDvlfvNjfKg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
