apiVersion: v1
kind: Secret
metadata:
  name: adguard-dns-secret
  namespace: network
type: Opaque
stringData:
  url: ENC[AES256_GCM,data:GK/uWsgeoSfcC9lQpXH5abYEww+BB3VsUuqdszs=,iv:4VuiiFXmKQRCRAn7gQiJ2Z8Hd4slTGPyqfidYJLQiNE=,tag:FYsrhaHObvUCbo5nRH996A==,type:str]
  user: ENC[AES256_GCM,data:Y9CncSAvp+o=,iv:UxbVz53NFYbYBBwUr1wquwoPKudXXvKZxgpKyWTbGGk=,tag:Ev2DISKMK9/gl+Pd40cRug==,type:str]
  password: ENC[AES256_GCM,data:4JyNDLyS5AItaY/8R5Hv84vKP2qCbnJLfcTbE6Xc70s=,iv:IhA1BMYfLC/jbU930tAi/J8diUHprQtfFNZfkIqQ0dI=,tag:vZMDi9Vzfh650yM92+ANGQ==,type:str]
sops:
  age:
    - recipient: age1y7nfred6vj25amp64z3x7m5d7vsuxvh5740zn0y0wdrx52tmrv3qwvhhua
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybmlzcU50NmFWcGxVYXhh
        VVpUU1RHc1lRNDRDdXpqU1o3Zmp3YU5tWXhVCjdlNEt3eFgzd1V4THNvaEZpY0hQ
        SjZEMmZsVHhOQlJVWlhlbEFTZ3dQeE0KLS0tIEV2SWg5dWwrUkZGWGlLYkcyOWg3
        Rjd4RnZ3QjJOZE0rWThXazE4Uzd6dTAKEsEPHXvAyX6U/7Vf78eVe4OPFzJ1o8fi
        C4oj5H3C2u3T0RCsBHNzQ+7fiaYjvm6vRL5m/Fq5C2EIVoGHSjzqBw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T23:02:01Z"
  mac: ENC[AES256_GCM,data:rjCJ5FjZvXbWVF0NWwXLFKNIiv2D6/NE4dgkpOIHTwQyR27AbC4gaDsgTG5xa4VLYsaljB78ht2APbK/0832rX7/PgT1N1D7TgtJdYIaqiQXpOvEfMvHB+RfvXuq7mVljtBDLt/r0GaumfqUWUC+XiVdXNG7km3mZRbM9HUePWo=,iv:92KyK/w7v8EFfERgkvjtbDZiQW5fwFvSPOpqiLSLRG0=,tag:Zg2vyruSs4jjtelGZmVwXg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
