apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:f+amuKabH5EuX8JyK43jZG7ZenmE86usbQRwc3sevTNhuwj5YGwlfw==,iv:HPYIoYvJPIlldUPSpYJDCe3POKBKME1vfgXbF2tQPto=,tag:XkH6APhebtbuXA3ORhrz0w==,type:str]
sops:
  age:
    - recipient: age1y7nfred6vj25amp64z3x7m5d7vsuxvh5740zn0y0wdrx52tmrv3qwvhhua
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNT2krakRmdDhOb2JZaDlh
        U0Y2b2ltYnJENmdFOVR5dlZ2WVNac0djcnhzCjFjemVMSVorcm5teVYwT1JobVc4
        THl0eVdXSEJXM0JDdHNxRFNMbFNTYXMKLS0tIEgxTEpFaDdMelNGZzlFQ1hLMXZO
        WnNlL240NHRFbm5tSTdtL3lvemJGVUUKTHQZ5v1ssrzz9dDdblqdX4xVSSsUxjoo
        bu89cUbv3QxMDDe4T+NLw0/URsb6GE3QZ66lA+IP6zK4VgLhx79CRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T12:30:06Z"
  mac: ENC[AES256_GCM,data:BB6yAzrwYW244NoB8TAezayup3yhyby4D+DXGrdNgf8WZpoHnO7gThjcj6vRYUPkAetMrfhuqhqunW/rw98iacYSvfVJk3lWyAt4U7C2Sj9Fpvv+yKMJo2ccBuaLwODuD7PxLm8+XoAGX2EVJAdR4BueQNXjjiiYjoYc4uZEOW4=,iv:snBO0tFZbUj57nlLRHjLuOuzFIWqG+VmsGzB0ibZ5mg=,tag:CY127jG0oiWBLmCODTm1og==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
