---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-config
  namespace: network
data:
  AdGuardHome.yaml: |
    bind_host: 0.0.0.0
    bind_port: 80
    dns:
      bind_hosts:
        - 0.0.0.0
      port: 53
      upstream_dns:
        - "https://1.1.1.1/dns-query"
        - "https://9.9.9.9/dns-query"
      bootstrap_dns:
        - 1.1.1.1
        - 9.9.9.9
      protection_enabled: true
      filtering_enabled: true
      safe_search:
        enabled: false
      parental_enabled: false
      safebrowsing_enabled: true
      blocking_mode: default
      blocked_response_ttl: 10
      cache_size: 4194304
      cache_ttl_min: 60
      cache_ttl_max: 86400
    filters:
      - enabled: true
        url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
        name: AdGuard DNS filter
        id: 1
      - enabled: true
        url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
        name: StevenBlack hosts
        id: 2
      - enabled: true
        url: https://someonewhocares.org/hosts/zero/hosts
        name: Dan Pollock's hosts
        id: 3
      - enabled: true
        url: https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
        name: NoCoin Filter
        id: 4
      - enabled: true
        url: https://www.malwaredomainlist.com/hostslist/hosts.txt
        name: MalwareDomainList.com Hosts List
        id: 5
    user_rules: []
    dhcp:
      enabled: false
    log:
      enabled: true
      file: ""
      max_backups: 0
      max_size: 100
      max_age: 3
      compress: false
      local_time: false
      verbose: false
    tls:
      enabled: false
    statistics:
      enabled: true
      interval: 1
    querylog:
      enabled: true
      interval: 2160h
      size_memory: 1000
    themes:
      - auto
