---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-work
  namespace: network
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-backup
  resources:
    requests:
      storage: 1Gi
