apiVersion: v1
kind: Secret
metadata:
  name: mealie-postgres
  namespace: default
type: Opaque
stringData:
  POSTGRES_USER: ENC[AES256_GCM,data:Ompt4ttp,iv:hx9Cxf6EM7BDQSSZ0o4oMBy96Z9V9WFpuDHJrD73+1w=,tag:iSZ3rq/az2sUqBHA9dVVnw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:fFNVkJGH,iv:GglWxNpljCOJTreAOWlQGRF0anCTt9lmmXiyhU5TsEA=,tag:sQGNwitjDU6ORUj5tLDoIA==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:QiAHpF/Z,iv:IXDZh0M7QzjqE9r885B6mJI887tYRGG4z0ZjEpJp5pg=,tag:yT+vcsttmD24wqpHGchzHw==,type:str]
sops:
  age:
    - recipient: age1y7nfred6vj25amp64z3x7m5d7vsuxvh5740zn0y0wdrx52tmrv3qwvhhua
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeU1ER3ZMUkpCakVQRUpn
        UWIvRW12NUlWZWlHUllBYUpXRjAyVUprbnkwCmEwZEo0bUdVYXZDK0ZFQm1sWGlS
        V3EvTmorQzZTbktkdmZ2djlqMDQ3dzAKLS0tIG5DMkx0VS9kZHEyUXFZK1RMMTlI
        aUZtNlJSaTlqeUdCVEdMVm5nUVJOc1EKPwnKykmozwQPCou6OEnmLnEtTy9hO6Pe
        jGhtBKCE8k2MpTgHHVcDsKDwQgca6ZrbpVAFy7NktQE39LLIe2s4oQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T17:23:38Z"
  mac: ENC[AES256_GCM,data:s1K6jXsLzcWQfK1BSNQD7FcRUxQf2LuEWNliY7RnmeAD8L0dgQI6ekRUcgubDIU4K/9bAymbv8+F0V9oygvIm8r7azp7djQkkmyV0+fNQJ9cxBXdB0Xn7qUDNs7FXeiZW1w6aHmWMDD0zq8qNbt3U4bQpeo5HXgyjH9FZ4msgqI=,iv:w45c8SMqrqnmKA9wSnL4dciuowYARuMfV+30gEQGCq0=,tag:mC7qj0eT1vLoaTf8i4M8+A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
